using Dapper;
using EsquireVRN.Models;
using EsquireVRN.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Data;
using System.Net.Mail;
using System.Text;

namespace EsquireVRN.Controllers
{
    public class HomeController : ControllerBase
    {
        [HttpPost]
        [Route("api/login")]
        public IActionResult Login([FromBody] LoginModel loginModel)
        {
            var lDetails = Shared.Login(loginModel.Email, loginModel.Password);
            if (lDetails.CustID == "Password_Mismatch")
            {
                string orgName = Shared.GetOrgName();

                string ipAddress = Convert.ToString(Request.HttpContext.Connection.RemoteIpAddress);
                string UserAgent = Request.Headers["User-Agent"];
                string timezone = TimeZoneInfo.Local.StandardName;
                if (string.IsNullOrEmpty(loginModel.timezone))
                {
                    timezone = loginModel.timezone;
                }
                string localtime = DateTime.Now.ToString("hh:mm tt");
                if (!string.IsNullOrEmpty(loginModel.localtime))
                {
                    localtime = loginModel.localtime;
                }
                string AdminMail = Shared.getAdminEMail();

                Shared.sendLoginMail("Someone is using your name to try and log in to the " + orgName + " account!",
                    "If this was <B><U>not</U></B> you trying to log in please " +
                    "contact " + orgName + ".<br/><br /><strong>More Information About this login attempt:</strong><br/>" +
                    "The IP Address was: " + ipAddress +
                    "<br />The user agent was: " + UserAgent +
                    "<br/ >From time zone: " + timezone + " @ " + localtime + " on his/her computer.<br />" +
                    "The server date and time was " + DateTime.Now.ToShortDateString() + " @ " + DateTime.Now.ToShortTimeString() +
                    "<br /><br />This E-Mail is automatically " +
                    "generated by the " + orgName + ".", loginModel.Email,
                    AdminMail, null, true);

                return StatusCode(401, new { error = "Incorrect password." });
            }
            else if (lDetails.CustID == "invalid")
            {
                return StatusCode(401, new { error = "Incorrect login data." });
            }

            if (lDetails.CustID == "fraudulent")
            {
                return StatusCode(400, new { error = "Your account has been marked fraudulent!" });
            }

            string token = Shared.GenerateToken(lDetails, "Customer");

            if (lDetails.IsLoggedIn)
            {
                Shared.RecordLogin(lDetails.CustID);
            }
            Shared.UpdateCartPrice(Convert.ToInt64(lDetails.CustID));
            List<DeliveryAddress> deliveryAderess = Shared.GetDeliveryAddresses(Convert.ToInt64(lDetails.CustID));
            bool hasDeliveryAddress = false;
            if (deliveryAderess.Count() > 0)
            {
                hasDeliveryAddress = true;
            }
            return Ok(new { token, name = lDetails.FirstName, HasDeliveryAddress = hasDeliveryAddress });
        }

        [HttpPost]
        [Route("api/customerRegistration")]
        public IActionResult RegisterCustomer([FromBody] CustomerRegistrationModel registration)
        {
            try
            {
                string strOrgID = "" + Shared.GetOrgID();
                string strAccountID = "", strCompany = "", strIDNo = "null", strVAT = "null", strSendEMails = "254", strBranch = "null", strNotes = "", strTitle = "";
                if (!string.IsNullOrEmpty(registration.Title))
                    strTitle = registration.Title;
                if (strTitle.ToLower() == "undefined" || string.IsNullOrWhiteSpace(strTitle))
                    strTitle = "Mr";

                if (!string.IsNullOrEmpty(registration.Notes) && registration.Notes.ToLower() != "undefined")
                    strNotes = registration.Notes;

                if (string.IsNullOrWhiteSpace(registration.FirstName))
                {
                    return BadRequest(new
                    {
                        message = "Your first name is required!"
                    });
                }
                if (string.IsNullOrWhiteSpace(registration.Surname))
                {
                    return BadRequest(new
                    {
                        message = "Your surname is required!"
                    });
                }
                if (!Shared.isEmailValid(registration.Email))
                {
                    return BadRequest(new
                    {
                        message = "Please provide a valid e-mail address!"
                    });
                }

                if (string.IsNullOrWhiteSpace(registration.Tel) || Shared.Val(registration.Tel) == "0")
                {
                    return BadRequest(new
                    {
                        message = "Your preferred contact no is required!"
                    });
                }

                if (string.IsNullOrWhiteSpace(registration.Password))
                {
                    return BadRequest(new
                    {
                        message = "Please provide a valid password!"
                    });
                }

                string aSQL = "SELECT CustID FROM WEBCustomer WHERE Email='" + registration.Email +
                    "' AND OrgID=" + strOrgID + ";SELECT AccountID FROM Accounts " +
                    "WHERE (OrgID = " + strOrgID + ") AND (Defalut = 1);";
                using (var db = new SqlConnection(Shared.connString))
                {
                    var result = db.QueryMultiple(aSQL);
                    var custId = result.Read<long?>().FirstOrDefault();
                    if (custId != null)
                    {
                        return BadRequest(new { error = "The e-mail address " + registration.Email + " already exists in our database." });
                    }
                    var accountDetails = result.Read().FirstOrDefault();
                    if (accountDetails != null)
                    {
                        strAccountID = Shared.Val(accountDetails.AccountID.ToString());
                    }
                }

                if (!string.IsNullOrEmpty(registration.VatNo) && registration.VatNo.ToLower() != "undefined")
                    strVAT = "N'" + registration.VatNo.Trim() + "'";
                if (!string.IsNullOrWhiteSpace(registration.Company) && registration.Company.ToLower() != "undefined")
                    strCompany = registration.Company.Trim();

                string strSQL = "INSERT INTO WEBCustomer (OrgID, FirstName, Surname, Tel, Tel2, " +
                       "Fax, Email, Company, [Password], Title, AccountID, IdNo, VatNo, SendEmails, DefaultOrgBranchID, Notes,UserType) " +
                       "OUTPUT Inserted.CustID VALUES (" + strOrgID + ",'" + registration.FirstName.Trim().Replace("\'", "\'\'") + "','" +
                       registration.Surname.Trim().Replace("\'", "\'\'") + "','" +
                       Shared.Val(registration.Tel) + "','" + Shared.Val(registration.Tel2) + "','" +
                       Shared.Val(registration.Fax) + "','" + registration.Email.Trim() + "','" +
                       strCompany + "','" +
                       registration.Password.Replace("\'", "\'\'") + "','" + registration.Title + "', " + strAccountID + "," +
                       strIDNo + "," + strVAT + ", " + strSendEMails + ", " + strBranch + ", N'" + strNotes.Trim() + "','Customer');";
                using (var db = new SqlConnection(Shared.connString))
                {
                    string strCustID = db.Query<string>(strSQL).FirstOrDefault();
                    if (!string.IsNullOrEmpty(strCustID))
                    {
                        DeliveryAddress dAddress = new()
                        {
                            ShippingCountry = registration.ShippingCountry,
                            ShippingAddress = registration.ShippingAddress,
                            ShippingDesc = registration.ShippingDesc,
                            ShippingType = registration.ShippingType,
                            Town = registration.Town,
                            Phone = registration.Phone,
                            PostalCode = registration.PostalCode,
                            CourierDirectKey = registration.CourierDirectKey,
                            ShippingddressIEID = registration.ShippingddressIEID,
                            CustID = Convert.ToInt64(strCustID)
                        };

                        Shared.SaveDeliveryAddress(dAddress);
                    }


                    #region Next we need to send the e-mail:
                    StringBuilder sbBody = new(Shared.GetWebConfigKeyValue("WelcomeEMailText"));
                    sbBody.Replace("{First Name}", registration.FirstName);
                    sbBody.Replace("{Surname}", registration.Surname);
                    sbBody.Replace("{Password}", registration.Password);
                    sbBody.Replace("{EMail}", registration.Email);
                    sbBody.Replace("{Title}", strTitle);
                    string strFromEMail = Shared.GetOrgEmail();
                    List<MailAddress> bcc = new() { new MailAddress("test@esquire.co.za"), new MailAddress("info@esquire.co.za"), new MailAddress("asgar@esquire.co.za") };

                    Shared.sendMail(Shared.GetOrgName() + " registration - Thank You!", sbBody.ToString(), Shared.splitEMailTo(registration.Email, registration.FirstName + " " + registration.Surname),
                    Shared.splitEMailFrom(strFromEMail, Shared.GetOrgName() + " - Registration"), bcc.ToArray(), null, false);
                    Shared.CheckFraudulent(registration.Email, strIDNo, registration.FirstName + " " + registration.Surname);
                    Shared.CheckFraudulentPassword(registration.Password, registration.FirstName + " " + registration.Surname);
                    #endregion
                }

                return Ok(new
                {
                    message = "Registration competed sucessfully."
                });
            }
            catch (Exception ex)
            {
                return StatusCode(422, new { error = ex.Message });
            }

        }

        [HttpGet]
        [Route("/api/GetHomepageSetup")]
        public IActionResult GetHomepageSetup()
        {
            List<HomepageSetup> setups = Shared.GetHomepageSetups();
            List<Banner> banners = Shared.GetBanners([.. setups.Select(x => x.ContentId)]);
            return Ok(new { setups, banners });
        }

        [HttpGet]
        [Authorize(Roles = "Customer")]
        [Route("api/GetProfile")]
        public IActionResult GetAccountDetail()
        {
            long CustomerID = Convert.ToInt64(User.Claims.First(claim => claim.Type == "CustomerID").Value);
            return Ok(Shared.GetCustomer(CustomerID));
        }

        [HttpPut]
        [Authorize(Roles = "Customer")]
        [Route("api/UpdateProfile")]
        public IActionResult Update([FromBody] Customer customer)
        {
            long CustomerID = Convert.ToInt64(User.Claims.First(claim => claim.Type == "CustomerID").Value);

            var oldCustomer = Shared.GetCustomer(CustomerID);
            if (oldCustomer == null)
            {
                return StatusCode(404, new { error = "Profile doesn't exist. Please check and try again." });
            }
            customer.UserType = "Customer";
            if (customer.DateCreated == null)
            {
                customer.DateCreated = oldCustomer.DateCreated;
            }
            if (string.IsNullOrWhiteSpace(customer.Company))
            {
                customer.Company = oldCustomer.Company;
            }
            var newCustomer = Shared.UpdateCustomer(CustomerID, customer);

            return Ok(new { message = "Profile updated successfully.", ProfileDetails = newCustomer });
        }

        [HttpPost]
        [Authorize]
        [Route("api/ChangePassword")]
        public IActionResult UpdatePassword([FromBody] ChangePassword changePassword)
        {
            string email = User.Identity.Name;
            string passwordVerified = "Invalid";
            if (User.IsInRole("Admin"))
            {
                passwordVerified = Shared.VerifyAdminPassword(email, changePassword.OldPassword);
            }
            else
            {
                passwordVerified = Shared.VerifyPassword(email, changePassword.OldPassword);
            }

            if (passwordVerified == "Fradulent")
            {
                return StatusCode(400, new { error = "Your account has been marked fraudulent!" });
            }
            else if (passwordVerified == "Invalid")
            {
                return StatusCode(400, new { error = "Invalid Password. Please check and try again." });
            }
            else if (passwordVerified == "Verified")
            {
                if (string.Compare(changePassword.NewPassword, changePassword.ConfirmPassword, true) == 0)
                {
                    bool passwordChanged = false;
                    if (User.IsInRole("Admin"))
                    {
                        passwordChanged = Shared.UpdateAdminPassword(email, changePassword.NewPassword);
                    }
                    else
                    {
                        passwordChanged = Shared.UpdatePassword(email, changePassword.NewPassword);
                    }
                    if (passwordChanged)
                    {
                        return Ok(new { message = "Password updated successfully." });
                    }
                    return StatusCode(500, new { error = "Something went wrong. Please try again." });
                }
                else
                {
                    return StatusCode(403, new { error = "New password and confirm password do not match." });
                }
            }
            return StatusCode(401, new { error = "Invalid Password. Please check and try again." });
        }

        [HttpPost]
        [Route("api/ResellerLogin")]
        public IActionResult ResellerLogin([FromBody] LoginModel loginModel)
        {
            try
            {
                var lDetails = Shared.ResellerLogin(loginModel.Email, loginModel.Password);

                if (lDetails.CustID == "invalid")
                {
                    string orgName = Shared.GetOrgName();

                    string ipAddress = Convert.ToString(Request.HttpContext.Connection.RemoteIpAddress);
                    string UserAgent = Request.Headers["User-Agent"];
                    string timezone = TimeZoneInfo.Local.StandardName;
                    if (string.IsNullOrEmpty(loginModel.timezone))
                    {
                        timezone = loginModel.timezone;
                    }
                    string localtime = DateTime.Now.ToString("hh:mm tt");
                    if (!string.IsNullOrEmpty(loginModel.localtime))
                    {
                        localtime = loginModel.localtime;
                    }
                    string AdminMail = Shared.getAdminEMail();

                    Shared.sendLoginMail("Someone is using your name to try and log in to the " + orgName + " account!",
                        "If this was <B><U>not</U></B> you trying to log in please " +
                        "contact " + orgName + ".<br/><br /><strong>More Information About this login attempt:</strong><br/>" +
                        "The IP Address was: " + ipAddress +
                        "<br />The user agent was: " + UserAgent +
                        "<br/ >From time zone: " + timezone + " @ " + localtime + " on his/her computer.<br />" +
                        "The server date and time was " + DateTime.Now.ToShortDateString() + " @ " + DateTime.Now.ToShortTimeString() +
                        "<br /><br />This E-Mail is automatically " +
                        "generated by the " + orgName + ".", loginModel.Email,
                        AdminMail, null, true);

                    return StatusCode(401, new { error = "Incorrect Credentials." });
                }
                if (lDetails.CustID == "fraudulent")
                {
                    return StatusCode(400, new { error = "Your account has been marked fraudulent!" });
                }

                string token = Shared.GenerateToken(lDetails, "Reseller");

                if (lDetails.IsLoggedIn)
                {
                    Shared.RecordLogin(lDetails.CustID);
                }
                Shared.UpdateCartPrice(Convert.ToInt64(lDetails.CustID));
                List<DeliveryAddress> deliveryAderess = Shared.GetDeliveryAddresses(Convert.ToInt64(lDetails.CustID));
                bool hasDeliveryAddress = false;
                if (deliveryAderess.Count() > 0)
                {
                    hasDeliveryAddress = true;
                }
                return Ok(new { token, name = lDetails.FirstName, HasDeliveryAddress = hasDeliveryAddress, AccountNumber = lDetails.AccountNumber });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { error = ex.Message });
            }
        }

        [HttpGet("api/GetOrgDetail")]
        [Authorize(Roles = "Reseller")]
        public IActionResult GetResellerProfile()
        {
            return Ok(Shared.GetOrgWebDetail());

        }

        [HttpPut]
        [Route("api/UpdateOrgDetail")]
        [Authorize(Roles = "Reseller")]
        public IActionResult UpdateOrgDetail([FromForm] OrgWebDetail webDetail)
        {
            try
            {
                var requestUrl = $"{Request.Scheme}://{Request.Host.Value}/";
                string imgUrl = "";
                if (!string.IsNullOrEmpty(webDetail.WebsiteLogoURL))
                {
                    imgUrl = webDetail.WebsiteLogoURL;
                }

                if (webDetail.Logo != null && webDetail.Logo.Length > 0)
                {
                    var fileSize = webDetail.Logo.Length;
                    if ((fileSize / 1048576.0) > 5)
                    {
                        return StatusCode(400, "Image exceeds 5mb size limit.");
                    }
                    else
                    {
                        var folderName = Path.Combine("Resources", "Images");
                        var pathToSave = Path.Combine(Directory.GetCurrentDirectory(), folderName);
                        if (!Directory.Exists(pathToSave))
                        {
                            Directory.CreateDirectory(pathToSave);
                        }
                        string imgname = webDetail.Logo.FileName;
                        var can_continue = false;
                        var extension = Path.GetExtension(imgname);
                        int i = 1;
                        while (!can_continue)
                        {
                            bool imgExists = System.IO.File.Exists(Path.Combine(pathToSave, imgname));
                            if (!imgExists)
                            {
                                can_continue = true;
                            }
                            if (imgExists)
                            {
                                if (imgname.Contains("-" + (i - 1) + extension))
                                {
                                    imgname = imgname.Replace("-" + (i - 1) + extension, "") + "-" + i + extension;
                                }
                                else
                                {
                                    imgname = imgname.Replace(extension, "") + "-" + i + extension;
                                }
                                i++;

                            }
                        }
                        string filePath = Path.Combine(pathToSave, imgname.Replace(" ", "-"));
                        using (FileStream fs = new FileStream(filePath, FileMode.Create))
                        {
                            webDetail.Logo.CopyTo(fs);
                        }
                        imgUrl = requestUrl + "Resources/Images/" + imgname.Replace(" ", "-");
                    }

                }
                webDetail.WebsiteLogoURL = imgUrl;
                OrgWebDetail detail = Shared.UpdateOrgDetail(webDetail);
                return Ok(detail);
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { error = ex.Message });
            }

        }

        [HttpGet("api/GetLogo")]
        public IActionResult GetLogo()
        {
            var logo = Shared.GetOrgLogo();
            return Ok(new { Logo = logo });
        }

        [HttpGet]
        [Route("api/ValidateToken")]
        public IActionResult ValidateToken()
        {

            if (User.Identity.IsAuthenticated)
            {
                return Ok(new { message = "Token is valid" });
            }
            return Unauthorized(new { error = "Token is invalid" });
        }
    }
}
