using Dapper;
using EsquireVRN.Models;
using EsquireVRN.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Net.Mail;
using System.Text;

namespace EsquireVRN.Controllers
{
    public class HomeController : ControllerBase
    {
        [HttpPost]
        [Route("api/login")]
        public IActionResult Login([FromBody] LoginModel loginModel)
        {
            var lDetails = Shared.Login(loginModel.Email, loginModel.Password);
            if (lDetails.CustID == "Password_Mismatch")
            {
                string orgName = Shared.GetOrgName();

                string ipAddress = Convert.ToString(Request.HttpContext.Connection.RemoteIpAddress);
                string UserAgent = Request.Headers["User-Agent"];
                string timezone = TimeZoneInfo.Local.StandardName;
                if (string.IsNullOrEmpty(loginModel.timezone))
                {
                    timezone = loginModel.timezone;
                }
                string localtime = DateTime.Now.ToString("hh:mm tt");
                if (!string.IsNullOrEmpty(loginModel.localtime))
                {
                    localtime = loginModel.localtime;
                }
                string AdminMail = Shared.getAdminEMail();

                Shared.sendLoginMail("Someone is using your name to try and log in to the " + orgName + " account!",
                    "If this was <B><U>not</U></B> you trying to log in please " +
                    "contact " + orgName + ".<br/><br /><strong>More Information About this login attempt:</strong><br/>" +
                    "The IP Address was: " + ipAddress +
                    "<br />The user agent was: " + UserAgent +
                    "<br/ >From time zone: " + timezone + " @ " + localtime + " on his/her computer.<br />" +
                    "The server date and time was " + DateTime.Now.ToShortDateString() + " @ " + DateTime.Now.ToShortTimeString() +
                    "<br /><br />This E-Mail is automatically " +
                    "generated by the " + orgName + ".", loginModel.Email,
                    AdminMail, null, true);

                return StatusCode(401, new { error = "Incorrect password." });
            }
            else if (lDetails.CustID == "invalid")
            {
                return StatusCode(401, new { error = "Incorrect login data." });
            }

            if (lDetails.CustID == "fraudulent")
            {
                return StatusCode(400, new { error = "Your account has been marked fraudulent!" });
            }

            string token = Shared.GenerateToken(lDetails, "Customer");

            if (lDetails.IsLoggedIn)
            {
                Shared.RecordLogin(lDetails.CustID);
            }
            Shared.UpdateCartPrice(Convert.ToInt64(lDetails.CustID));
            List<DeliveryAddress> deliveryAderess = Shared.GetDeliveryAddresses(Convert.ToInt64(lDetails.CustID));
            bool hasDeliveryAddress = false;
            if (deliveryAderess.Count() > 0)
            {
                hasDeliveryAddress = true;
            }
            return Ok(new { token, name = lDetails.FirstName, HasDeliveryAddress = hasDeliveryAddress });
        }

        [HttpPost]
        [Route("api/customerRegistration")]
        public IActionResult RegisterCustomer([FromBody] CustomerRegistrationModel registration)
        {
            try
            {
                string strOrgID = "" + Shared.GetOrgID();
                string strAccountID = "", strCompany = "", strIDNo = "null", strVAT = "null", strSendEMails = "254", strBranch = "null", strNotes = "", strTitle = "";
                if (!string.IsNullOrEmpty(registration.Title))
                    strTitle = registration.Title;
                if (strTitle.ToLower() == "undefined" || string.IsNullOrWhiteSpace(strTitle))
                    strTitle = "Mr";

                if (!string.IsNullOrEmpty(registration.Notes) && registration.Notes.ToLower() != "undefined")
                    strNotes = registration.Notes;

                if (string.IsNullOrWhiteSpace(registration.FirstName))
                {
                    return BadRequest(new
                    {
                        message = "Your first name is required!"
                    });
                }
                if (string.IsNullOrWhiteSpace(registration.Surname))
                {
                    return BadRequest(new
                    {
                        message = "Your surname is required!"
                    });
                }
                if (!Shared.isEmailValid(registration.Email))
                {
                    return BadRequest(new
                    {
                        message = "Please provide a valid e-mail address!"
                    });
                }

                if (string.IsNullOrWhiteSpace(registration.Tel) || Shared.Val(registration.Tel) == "0")
                {
                    return BadRequest(new
                    {
                        message = "Your preferred contact no is required!"
                    });
                }

                if (string.IsNullOrWhiteSpace(registration.Password))
                {
                    return BadRequest(new
                    {
                        message = "Please provide a valid password!"
                    });
                }

                string aSQL = "SELECT CustID FROM WEBCustomer WHERE Email='" + registration.Email +
                    "' AND OrgID=" + strOrgID + ";SELECT AccountID FROM Accounts " +
                    "WHERE (OrgID = " + strOrgID + ") AND (Defalut = 1);";
                using (var db = new SqlConnection(Shared.connString))
                {
                    var result = db.QueryMultiple(aSQL);
                    var custId = result.Read<long?>().FirstOrDefault();
                    if (custId != null)
                    {
                        return BadRequest(new { error = "The e-mail address " + registration.Email + " already exists in our database." });
                    }
                    var accountDetails = result.Read().FirstOrDefault();
                    if (accountDetails != null)
                    {
                        strAccountID = Shared.Val(accountDetails.AccountID.ToString());
                    }
                }

                if (!string.IsNullOrEmpty(registration.VatNo) && registration.VatNo.ToLower() != "undefined")
                    strVAT = "N'" + registration.VatNo.Trim() + "'";
                if (!string.IsNullOrWhiteSpace(registration.Company) && registration.Company.ToLower() != "undefined")
                    strCompany = registration.Company.Trim();

                string strSQL = "INSERT INTO WEBCustomer (OrgID, FirstName, Surname, Tel, Tel2, " +
                       "Fax, Email, Company, [Password], Title, AccountID, IdNo, VatNo, SendEmails, DefaultOrgBranchID, Notes,UserType) " +
                       "OUTPUT Inserted.CustID VALUES (" + strOrgID + ",'" + registration.FirstName.Trim().Replace("\'", "\'\'") + "','" +
                       registration.Surname.Trim().Replace("\'", "\'\'") + "','" +
                       Shared.Val(registration.Tel) + "','" + Shared.Val(registration.Tel2) + "','" +
                       Shared.Val(registration.Fax) + "','" + registration.Email.Trim() + "','" +
                       strCompany + "','" +
                       registration.Password.Replace("\'", "\'\'") + "','" + registration.Title + "', " + strAccountID + "," +
                       strIDNo + "," + strVAT + ", " + strSendEMails + ", " + strBranch + ", N'" + strNotes.Trim() + "','Customer');";
                using (var db = new SqlConnection(Shared.connString))
                {
                    string strCustID = db.Query<string>(strSQL).FirstOrDefault();
                    if (!string.IsNullOrEmpty(strCustID))
                    {
                        DeliveryAddress dAddress = new()
                        {
                            ShippingCountry = registration.ShippingCountry,
                            ShippingAddress = registration.ShippingAddress,
                            ShippingDesc = registration.ShippingDesc,
                            ShippingType = registration.ShippingType,
                            Town = registration.Town,
                            Phone = registration.Phone,
                            PostalCode = registration.PostalCode,
                            CourierDirectKey = registration.CourierDirectKey,
                            ShippingddressIEID = registration.ShippingddressIEID,
                            CustID = Convert.ToInt64(strCustID)
                        };

                        Shared.SaveDeliveryAddress(dAddress);
                    }


                    #region Next we need to send the e-mail:
                    StringBuilder sbBody = new(Shared.GetWebConfigKeyValue("WelcomeEMailText"));
                    sbBody.Replace("{First Name}", registration.FirstName);
                    sbBody.Replace("{Surname}", registration.Surname);
                    sbBody.Replace("{Password}", registration.Password);
                    sbBody.Replace("{EMail}", registration.Email);
                    sbBody.Replace("{Title}", strTitle);
                    string strFromEMail = Shared.GetOrgEmail();
                    List<MailAddress> bcc = new() { new MailAddress("test@esquire.co.za"), new MailAddress("info@esquire.co.za"), new MailAddress("asgar@esquire.co.za") };

                    Shared.sendMail(Shared.GetOrgName() + " registration - Thank You!", sbBody.ToString(), Shared.splitEMailTo(registration.Email, registration.FirstName + " " + registration.Surname),
                    Shared.splitEMailFrom(strFromEMail, Shared.GetOrgName() + " - Registration"), bcc.ToArray(), null, false);
                    Shared.CheckFraudulent(registration.Email, strIDNo, registration.FirstName + " " + registration.Surname);
                    Shared.CheckFraudulentPassword(registration.Password, registration.FirstName + " " + registration.Surname);
                    #endregion
                }

                return Ok(new
                {
                    message = "Registration competed sucessfully."
                });
            }
            catch (Exception ex)
            {
                return StatusCode(422, new { error = ex.Message });
            }

        }

        [HttpGet]
        [Route("GetHomepageSetup")]
        public IActionResult GetHomepageSetup()
        {
            List<HomepageSetup> setups = Shared.GetHomepageSetups();
            List<Banner> banners = Shared.GetBanners([.. setups.Select(x => x.ContentId)]);
            return Ok(new { setups, banners });
        }
    }
}
